name: test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install -r requirements.txt -r dev-requirements.txt

    - name: Install package
      run: |
        pip install .

    - name: Run unit tests
      run: pytest .
